# Generated by Django 5.0.6 on 2024-07-18 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id_cargo', models.AutoField(db_column='idCargo', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id_estado_civil', models.AutoField(db_column='idEstadoCivil', primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id_genero', models.AutoField(db_column='idGenero', primary_key=True, serialize=False)),
                ('genero', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('nombre', models.CharField(max_length=255)),
                ('apellido_paterno', models.CharField(max_length=255)),
                ('apellido_materno', models.CharField(max_length=255)),
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=255)),
                ('comuna', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=255)),
                ('fecha_ingreso', models.DateField()),
                ('sueldo_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cargo', models.ForeignKey(db_column='idCargo', on_delete=django.db.models.deletion.CASCADE, to='colaboradores.cargo')),
            ],
        ),
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('id_departamento', models.AutoField(db_column='idDepartamento', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('jefe_departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jefe_departamento', to='colaboradores.colaborador')),
            ],
        ),
        migrations.AddField(
            model_name='colaborador',
            name='departamento',
            field=models.ForeignKey(db_column='idDepartamento', on_delete=django.db.models.deletion.CASCADE, to='colaboradores.departamentos'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colaboradores.departamentos'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='estado_civil',
            field=models.ForeignKey(db_column='idEstadoCivil', on_delete=django.db.models.deletion.CASCADE, to='colaboradores.estadocivil'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='id_genero',
            field=models.ForeignKey(db_column='idGenero', on_delete=django.db.models.deletion.CASCADE, to='colaboradores.genero'),
        ),
    ]
