# Generated by Django 5.0.6 on 2024-07-05 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanvip_rh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('formula_calculo', models.TextField()),
                ('frecuencia_medicion', models.CharField(choices=[('mensual', 'Mensual'), ('trimestral', 'Trimestral'), ('anual', 'Anual')], max_length=255)),
                ('meta_objetivo', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Ausencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_ausencia', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('justificacion', models.TextField()),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cleanvip_rh.colaborador')),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('jefe_departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cleanvip_rh.colaborador')),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('sueldo_minimo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sueldo_maximo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cleanvip_rh.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='DatoIndicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cleanvip_rh.indicador')),
            ],
        ),
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('indicador_medicion', models.CharField(max_length=255)),
                ('valor_objetivo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cleanvip_rh.colaborador')),
            ],
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('usuario', models.ManyToManyField(to='cleanvip_rh.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='SeguimientoMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_seguimiento', models.DateField()),
                ('valor_alcanzado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observaciones', models.TextField()),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cleanvip_rh.meta')),
            ],
        ),
    ]
