# Generated by Django 5.0.6 on 2024-07-05 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanvip_rh', '0002_indicador_ausencia_departamento_cargo_datoindicador_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('jefe_departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jefe_departamento', to='cleanvip_rh.colaborador')),
            ],
        ),
        migrations.AddField(
            model_name='colaborador',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cleanvip_rh.departamentos'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cleanvip_rh.departamentos'),
        ),
        migrations.DeleteModel(
            name='Departamento',
        ),
    ]
