# Generated by Django 5.0.6 on 2024-07-05 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanvip_rh', '0003_departamentos_colaborador_departamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacitacion',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
