# Generated by Django 5.0.6 on 2024-07-05 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanvip_rh', '0004_alter_capacitacion_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacitacion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
